import { useEffect, useState } from 'react'
import axios from 'axios'
import { ArrowUpRight, Camera, Check, Clock3, Landmark, LocateFixed, Menu, Play, Sparkles, Video, X } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import heroFallback from './assets/hero.png'
import templeImage from '../Temple.jpg'
import templeImageOne from '../Temple1.jpg'
import templeImageThree from '../Temple3.jpg'
import ganeshChaturthiImage from '../Ganeshchaturthi.jpg'
import './App.css'

const DEFAULT_CONTENT = {
  hero: templeImage,
  history: 'Temple history and heritage details will be updated by temple administration.',
  timings: 'Information will be updated by temple administration.', pooja: 'Information will be updated by temple administration.',
  maps: 'https://www.google.com/maps/search/?api=1&query=Sri+Lakshmi+Vinayagar+Temple+Thiruninravur+602024', video: '', facebook: '', instagram: '',
  contact: 'Please contact the temple administration for current visitor information.',
  gallery: [
    { title: 'Temple exterior', category: 'Temple exterior', image: templeImage },
    { title: 'Sacred detail', category: 'Sanctum', image: templeImageOne },
    { title: 'Festival light', category: 'Decorations', image: templeImageThree },
    { title: 'Vinayagar Chaturthi 2026', category: 'Festival', image: ganeshChaturthiImage },
  ], festivals: [
    { name: 'Vinayagar Chaturthi', month: 'Tamil month / Gregorian month to be confirmed', detail: 'Festival details will be updated by temple administration.' },
    { name: 'Sankatahara Chaturthi', month: 'Monthly observance', detail: 'Festival details will be updated by temple administration.' },
    { name: 'Temple observances', month: 'Schedule to be confirmed', detail: 'Please check with the temple administration before planning a visit.' },
  ],
}
const COPY = {
  en: { about: 'ABOUT THE TEMPLE', plan: 'PLAN YOUR VISIT', festivals: 'FESTIVALS & OBSERVANCES', gallery: 'FROM THE TEMPLE', location: 'FIND YOUR WAY', contact: 'STAY CONNECTED', place: 'THIRUNINRAVUR · CHENNAI', hero: 'A sacred space for', heroEm: 'devotion & blessings.', subtitle: 'Sri Lakshmi Vinayagar Temple', visit: 'Plan your visit', directions: 'Get directions', hours: "TODAY'S TEMPLE HOURS", verify: 'Verify before you visit', view: 'View timings', scroll: 'SCROLL TO DISCOVER', aboutTitle: 'Where every prayer finds its way home.', aboutLead: 'Sri Lakshmi Vinayagar Temple is a place for quiet devotion, auspicious beginnings, and community in Thiruninravur.', info: 'Temple information', timingTitle: 'Come as you are. Leave with peace.', timingNote: 'Timings may change during festivals and special occasions. Please contact the temple administration before visiting.', daily: 'DAILY TEMPLE HOURS', pooja: 'POOJAS & OFFERINGS', celebration: 'Moments of celebration.', calendar: 'Mark your calendar with devotion. Schedules are confirmed by administration.', glimpse: 'A glimpse of the sacred.', curated: 'Authentic images will be curated by temple administration.', find: 'Make your way to Thiruninravur.', openMaps: 'Open in Google Maps', connected: 'Keep the temple close at heart.', administration: 'Please contact the temple administration for current visitor information.', video: 'Temple video will be updated by administration' },
  ta: { about: 'கோயிலைப் பற்றி', plan: 'வருகையைத் திட்டமிடுங்கள்', festivals: 'திருவிழாக்கள் மற்றும் வழிபாடுகள்', gallery: 'கோயில் காட்சிகள்', location: 'வழியைக் கண்டறியுங்கள்', contact: 'தொடர்பில் இருங்கள்', place: 'திருநின்றவூர் · சென்னை', hero: 'பக்தியும் அருளும்', heroEm: 'நிறைந்த புனிதத் தலம்.', subtitle: 'ஸ்ரீ லக்ஷ்மி விநாயகர் ஆலயம்', visit: 'வருகையைத் திட்டமிடுங்கள்', directions: 'வழியைப் பெறுங்கள்', hours: 'இன்றைய கோயில் நேரம்', verify: 'வருவதற்கு முன் உறுதிசெய்யவும்', view: 'நேரங்களைக் காண்க', scroll: 'கீழே காண்க', aboutTitle: 'ஒவ்வொரு பிரார்த்தனையும் இல்லம் சேரும் இடம்.', aboutLead: 'திருநின்றவூரில் அமைந்துள்ள ஸ்ரீ லக்ஷ்மி விநாயகர் ஆலயம் அமைதியான பக்தி, நல்ல தொடக்கம் மற்றும் சமூகத்தின் புனிதத் தலமாகும்.', info: 'கோயில் தகவல்', timingTitle: 'எளிமையாக வாருங்கள். அமைதியுடன் செல்லுங்கள்.', timingNote: 'திருவிழாக்கள் மற்றும் சிறப்பு நாட்களில் நேரங்கள் மாறலாம். வருவதற்கு முன் கோயில் நிர்வாகத்தைத் தொடர்புகொள்ளவும்.', daily: 'தினசரி கோயில் நேரம்', pooja: 'பூஜைகள் மற்றும் காணிக்கைகள்', celebration: 'கொண்டாட்டத்தின் தருணங்கள்.', calendar: 'பக்தியுடன் உங்கள் நாட்காட்டியில் குறித்துக் கொள்ளுங்கள். நேரங்கள் நிர்வாகத்தால் உறுதி செய்யப்படும்.', glimpse: 'புனிதத்தின் ஒரு பார்வை.', curated: 'உண்மையான புகைப்படங்கள் கோயில் நிர்வாகத்தால் சேர்க்கப்படும்.', find: 'திருநின்றவூருக்கு வாருங்கள்.', openMaps: 'Google Maps-ல் திறக்கவும்', connected: 'கோயிலை மனதிற்கு அருகில் வைத்திருங்கள்.', administration: 'தற்போதைய வருகைத் தகவலுக்கு கோயில் நிர்வாகத்தைத் தொடர்புகொள்ளவும்.', video: 'கோயில் காணொளி நிர்வாகத்தால் சேர்க்கப்படும்' },
}
const FESTIVAL_TAMIL = ['விநாயகர் சதுர்த்தி', 'சங்கடஹர சதுர்த்தி', 'கோயில் வழிபாடுகள்']
const adminSchema = z.object({ hero: z.string().url('Enter a valid image URL'), maps: z.string().url('Enter a valid Google Maps URL'), video: z.string().refine((value) => !value || value.includes('youtube.com/embed/'), 'Use a YouTube embed URL'), history: z.string().min(20), timings: z.string().min(5), pooja: z.string().min(5), contact: z.string().min(5), facebook: z.string().url().or(z.literal('')), instagram: z.string().url().or(z.literal('')) })

function App() {
  const [content, setContent] = useState(() => { const saved = JSON.parse(localStorage.getItem('slv-content') || 'null'); if (!saved) return DEFAULT_CONTENT; const gallery = saved.gallery?.map((image, index) => image.image?.includes('unsplash') ? { ...image, image: DEFAULT_CONTENT.gallery[index]?.image || templeImage } : image).filter((image) => image.image) || DEFAULT_CONTENT.gallery; if (!gallery.some((image) => image.image === ganeshChaturthiImage)) gallery.push(DEFAULT_CONTENT.gallery[3]); return { ...saved, hero: saved.hero?.includes('1548013146') || saved.hero?.includes('unsplash') || saved.hero?.includes('temple-exterior') ? DEFAULT_CONTENT.hero : saved.hero, gallery } })
  const [admin, setAdmin] = useState(false); const [loginOpen, setLoginOpen] = useState(false); const [lightbox, setLightbox] = useState(null); const [mobileOpen, setMobileOpen] = useState(false); const [toast, setToast] = useState(''); const [loginError, setLoginError] = useState('')
  const [apiStatus, setApiStatus] = useState('offline')
  const [language, setLanguage] = useState(() => localStorage.getItem('slv-language') || 'ta')
  const ui = COPY[language]
  const { register, handleSubmit, reset, formState: { errors } } = useForm({ resolver: zodResolver(adminSchema), defaultValues: content })
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 2600); return () => clearTimeout(timer) } }, [toast])
  useEffect(() => { document.documentElement.lang = language === 'ta' ? 'ta' : 'en'; document.title = language === 'ta' ? 'ஸ்ரீ லக்ஷ்மி விநாயகர் ஆலயம்' : 'Sri Lakshmi Vinayagar Temple' }, [language])
  useEffect(() => { const endpoint = import.meta.env.VITE_TEMPLE_API_ENDPOINT; if (!endpoint) return; axios.get(endpoint).then(() => setApiStatus('online')).catch(() => setApiStatus('offline')) }, [])
  const save = (values) => { const next = { ...content, ...values }; setContent(next); localStorage.setItem('slv-content', JSON.stringify(next)); setToast('Content saved to this device') }
  const nav = ['About Temple', 'Timings & Poojas', 'Festivals', 'Gallery', 'Location', 'Contact']
  const scrollTo = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMobileOpen(false) }
  const login = (event) => { event.preventDefault(); if (event.currentTarget.user.value === 'admin' && event.currentTarget.password.value === 'H@ri9831') { setAdmin(true); setLoginOpen(false); setLoginError('') } else setLoginError('Incorrect demo credentials') }
  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="#home"><span className="brand-mark">ॐ</span><span><b>{language === 'ta' ? 'ஸ்ரீ லக்ஷ்மி' : 'Sri Lakshmi'}</b><small>{language === 'ta' ? 'விநாயகர் ஆலயம்' : 'VINAYAGAR TEMPLE'}</small></span></a><nav className={mobileOpen ? 'nav open' : 'nav'}>{nav.map((item, index) => <button key={item} onClick={() => scrollTo(item.split(' ')[0].toLowerCase())}>{language === 'ta' ? [ui.about, ui.plan, ui.festivals, ui.gallery, ui.location, ui.contact][index] : item}</button>)}<button className="language-switch" onClick={() => { const next = language === 'en' ? 'ta' : 'en'; setLanguage(next); localStorage.setItem('slv-language', next) }} aria-label="Change language">{language === 'en' ? 'தமிழ்' : 'English'}</button><button className="admin-link" onClick={() => admin ? setAdmin(false) : setLoginOpen(true)}>{admin ? 'Exit admin' : 'Admin login'} <ArrowUpRight size={15}/></button></nav><button className="menu-btn" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle navigation">{mobileOpen ? <X/> : <Menu/>}</button></header>
    <main>
      <section className="hero" id="home" style={{ backgroundImage: `linear-gradient(90deg, rgba(35,18,13,.82), rgba(35,18,13,.12)), url(${content.hero}), url(${heroFallback})` }}><div className="hero-copy"><p className="eyebrow">{ui.place}</p><h1>{ui.hero}<br/><em>{ui.heroEm}</em></h1><p className="hero-sub">{ui.subtitle}</p><div className="hero-actions"><button className="button light" onClick={() => scrollTo('location')}>{ui.visit} <ArrowUpRight size={17}/></button><a className="button outline" href={content.maps} target="_blank" rel="noreferrer">{ui.directions} <LocateFixed size={16}/></a></div><p className="mantra">ॐ Gam Ganapataye Namah</p></div><div className="hero-note"><span className="note-icon"><Clock3 size={18}/></span><div><small>{ui.hours}</small><strong>{apiStatus === 'online' ? (language === 'ta' ? 'தற்போதைய தகவலைப் பார்க்கவும்' : 'Check current listing') : ui.verify}</strong><a href="#timings">{ui.view} <ArrowUpRight size={14}/></a></div></div><div className="hero-scroll">{ui.scroll} <span>↓</span></div></section>
      <section className="welcome band" id="about"><div className="section-kicker">01 <span>{ui.about}</span></div><div className="about-grid"><div><h2>{ui.aboutTitle}</h2><p className="lead">{ui.aboutLead}</p><p>{language === 'ta' ? 'கோயிலின் வரலாறு மற்றும் பாரம்பரிய விவரங்கள் கோயில் நிர்வாகத்தால் புதுப்பிக்கப்படும்.' : content.history}</p><button className="text-link" onClick={() => setAdmin(true)}>{ui.info} <ArrowUpRight size={16}/></button></div><div className="heritage-image"><img src={content.gallery[0]?.image || templeImage} onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = templeImage }} alt={language === 'ta' ? 'கோயில் வெளிப்புறம்' : 'Hindu temple exterior'}/><span>{language === 'ta' ? 'கோயில் பாரம்பரியம்' : 'Temple heritage'}</span></div></div></section>
      <section className="timing band dark" id="timings"><div className="section-kicker light-kicker">02 <span>{ui.plan}</span></div><div className="timing-grid"><div><h2>{ui.timingTitle}</h2><p>{ui.timingNote}</p></div><div className="timing-card"><div className="timing-row"><Clock3/><span><small>{ui.daily}</small><b>{language === 'ta' ? 'தகவல்கள் நிர்வாகத்தால் புதுப்பிக்கப்படும்.' : content.timings}</b></span></div><div className="timing-row"><Sparkles/><span><small>{ui.pooja}</small><b>{language === 'ta' ? 'தகவல்கள் நிர்வாகத்தால் புதுப்பிக்கப்படும்.' : content.pooja}</b></span></div></div></div></section>
      <section className="festivals band" id="festivals"><div className="section-kicker">03 <span>{ui.festivals}</span></div><div className="heading-row"><h2>{ui.celebration}</h2><p>{ui.calendar}</p></div><div className="festival-list">{content.festivals.map((festival, index) => <article className="festival" key={festival.name}><span className="festival-no">0{index + 1}</span><div><h3>{language === 'ta' ? FESTIVAL_TAMIL[index] : festival.name}</h3><p className="month">{language === 'ta' ? 'மாதம் / தேதி நிர்வாகத்தால் உறுதி செய்யப்படும்' : festival.month}</p><p>{language === 'ta' ? 'திருவிழா விவரங்கள் கோயில் நிர்வாகத்தால் புதுப்பிக்கப்படும்.' : festival.detail}</p></div><ArrowUpRight className="festival-arrow"/></article>)}</div></section>
      <section className="gallery band" id="gallery"><div className="section-kicker light-kicker">04 <span>{ui.gallery}</span></div><div className="heading-row"><h2>{ui.glimpse}</h2><p>{ui.curated}</p></div><div className="gallery-grid">{content.gallery.map((image, index) => <button className={`gallery-item item-${index}`} key={image.image} onClick={() => setLightbox(image)}><img src={image.image || templeImage} onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = templeImage }} alt={language === 'ta' ? 'இந்து கோயில் புகைப்படம்' : `${image.title}, Hindu temple`}/><span>{language === 'ta' ? 'கோயில் காட்சி' : image.title}<ArrowUpRight size={15}/></span></button>)}</div></section>
      <section className="visit band" id="location"><div className="section-kicker">05 <span>{ui.location}</span></div><div className="visit-grid"><div><h2>{ui.find}</h2><p className="address"><Landmark size={20}/> {language === 'ta' ? 'ஸ்ரீ லக்ஷ்மி விநாயகர் ஆலயம்' : 'Sri Lakshmi Vinayagar Temple'}<br/><span>Thiruninravur, Chennai – 602024<br/>{language === 'ta' ? 'தமிழ்நாடு, இந்தியா' : 'Tamil Nadu, India'}</span></p><a href={content.maps} target="_blank" rel="noreferrer" className="button maroon">{ui.openMaps} <ArrowUpRight size={16}/></a></div><div className="map-art"><div className="map-pin"><LocateFixed size={20}/></div><div className="map-label">{language === 'ta' ? <>ஸ்ரீ லக்ஷ்மி<br/><b>விநாயகர் ஆலயம்</b></> : <>SRI LAKSHMI<br/><b>VINAYAGAR TEMPLE</b></>}</div></div></div></section>
      <section className="contact band dark" id="contact"><div className="contact-grid"><div><div className="section-kicker light-kicker">06 <span>{ui.contact}</span></div><h2>{ui.connected}</h2><p>{language === 'ta' ? 'தற்போதைய வருகைத் தகவலுக்கு கோயில் நிர்வாகத்தைத் தொடர்புகொள்ளவும்.' : content.contact}</p><div className="socials">{content.facebook && <a href={content.facebook} target="_blank" rel="noreferrer"><Camera/></a>}{content.instagram && <a href={content.instagram} target="_blank" rel="noreferrer"><Camera/></a>}<a href={content.video || '#'} target="_blank" rel="noreferrer"><Video/></a></div></div><div className="video-box">{content.video ? <iframe src={content.video} title="Temple video" allowFullScreen/> : <><Play size={24}/><span>{ui.video}</span></>}</div></div></section>
    </main>
    <footer><div className="footer-brand"><span className="brand-mark">ॐ</span><div><b>{language === 'ta' ? 'ஸ்ரீ லக்ஷ்மி விநாயகர் ஆலயம்' : 'Sri Lakshmi Vinayagar Temple'}</b><small>Thiruninravur, Chennai – 602024</small></div></div><p>{language === 'ta' ? <>கோயில் நேரங்கள், பூஜைகள் மற்றும் திருவிழா அட்டவணைகள் மாறக்கூடும்.<br/>வருவதற்கு முன் கோயில் நிர்வாகத்திடம் உறுதிசெய்யவும்.</> : <>Temple timings, poojas and festival schedules are subject to change.<br/>Please confirm with the temple administration before visiting.</>}</p><span>© 2026 · {language === 'ta' ? 'பக்தியுடன் உருவாக்கப்பட்டது' : 'Made with devotion'}</span></footer>
    {loginOpen && <div className="modal-backdrop"><form className="login-modal" onSubmit={login}><button className="close" type="button" onClick={() => setLoginOpen(false)}><X/></button><span className="brand-mark">ॐ</span><h2>Temple administration</h2><p>Static demonstration login</p><input name="user" placeholder="Username" required/><input name="password" type="password" placeholder="Password" required/><button className="button maroon">Sign in <ArrowUpRight size={16}/></button>{loginError && <small className="error">{loginError}</small>}<small className="security-note">A frontend-only password is not secure for production. Use Firebase Auth, Supabase Auth, or a custom server before deploying publicly.</small></form></div>}
    {admin && <aside className="admin-panel"><div className="admin-head"><div><span className="section-kicker">ADMIN MODE</span><h2>Temple content</h2></div><button onClick={() => setAdmin(false)}><X/></button></div><form onSubmit={handleSubmit(save)}><label>Hero image URL<input {...register('hero')}/></label>{errors.hero && <small className="error">{errors.hero.message}</small>}<label>History<textarea {...register('history')}/></label><label>Daily timings<textarea {...register('timings')}/></label><label>Poojas<textarea {...register('pooja')}/></label><label>Google Maps URL<input {...register('maps')}/></label><label>Contact details<textarea {...register('contact')}/></label><label>YouTube embed URL<input {...register('video')} placeholder="https://www.youtube.com/embed/..."/></label><label>Facebook URL<input {...register('facebook')}/></label><label>Instagram URL<input {...register('instagram')}/></label><div className="admin-actions"><button type="submit" className="button maroon"><Check size={16}/> Save changes</button><button type="button" className="reset" onClick={() => { if (confirm('Reset all content to defaults?')) { localStorage.removeItem('slv-content'); setContent(DEFAULT_CONTENT); reset(DEFAULT_CONTENT); setToast('Content reset to defaults') } }}>Reset defaults</button></div></form></aside>}
    {lightbox && <div className="lightbox" onClick={() => setLightbox(null)}><button onClick={() => setLightbox(null)}><X/></button><img src={lightbox.image} alt={lightbox.title}/><span>{lightbox.title}</span></div>}{toast && <div className="toast"><Check size={16}/> {toast}</div>}
  </div>
}
export default App
